<?php

########################################################################
# Extension Manager/Repository config file for ext: "mobileappfactory"
#
# Auto generated by Extension Builder 2011-10-20
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Mobile App Factory',
	'description' => 'An extension that turns Typo3 into a development tool for mobile applications (apps). ',
	'category' => 'module',
	'author' => 'Tim Wentzlau',
	'author_email' => 'tim.wentzlau@auxilior.com',
	'author_company' => 'Auxilior Technology PF',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
			'phonegap'=>'',
			'jqmfluidtemplates'=>''
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>